<a href="https://colab.research.google.com/github/hakanmetei/hakanmetei/blob/main/colabNotlar%C4%B1m.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import numpy as np


In [7]:
np.array(1,2)

TypeError: Cannot interpret '2' as a data type

# Task
Teach me NumPy from scratch, explaining its functions and how to use them.

## Numpy'a giriş

### Subtask:
NumPy'ın ne olduğunu, neden önemli olduğunu ve temel özelliklerini açıklayın.


**Reasoning**:
The subtask is to explain what NumPy is, why it's important, and its basic features. I will provide a markdown cell explaining these concepts based on the instructions.



## Numpy dizileri (ndarray)

### Subtask:
NumPy dizilerinin (ndarray) nasıl oluşturulduğunu, farklı boyutlardaki dizileri ve temel dizi özelliklerini (şekil, boyut, veri tipi) gösterin.


**Reasoning**:
Create and display one-dimensional, two-dimensional, and three-dimensional NumPy arrays, along with their shape, dimension, and data type, as per the instructions.



In [9]:
# 1. Tek boyutlu bir NumPy dizisi oluşturun
tek_boyutlu_dizi = np.array([1, 2, 3, 4, 5])

# 2. İki boyutlu (matris) bir NumPy dizisi oluşturun
iki_boyutlu_dizi = np.array([[1, 2, 3], [4, 5, 6]])

# 3. Üç boyutlu bir NumPy dizisi oluşturun
uc_boyutlu_dizi = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# 4. Her oluşturulan dizinin şeklini (shape), boyutunu (ndim) ve veri tipini (dtype) yazdırın.
print("Tek Boyutlu Dizi:")
print("Dizi:", tek_boyutlu_dizi)
print("Şekil:", tek_boyutlu_dizi.shape)
print("Boyut:", tek_boyutlu_dizi.ndim)
print("Veri Tipi:", tek_boyutlu_dizi.dtype)
print("-" * 20)

print("İki Boyutlu Dizi:")
print("Dizi:", iki_boyutlu_dizi)
print("Şekil:", iki_boyutlu_dizi.shape)
print("Boyut:", iki_boyutlu_dizi.ndim)
print("Veri Tipi:", iki_boyutlu_dizi.dtype)
print("-" * 20)

print("Üç Boyutlu Dizi:")
print("Dizi:", uc_boyutlu_dizi)
print("Şekil:", uc_boyutlu_dizi.shape)
print("Boyut:", uc_boyutlu_dizi.ndim)
print("Veri Tipi:", uc_boyutlu_dizi.dtype)
print("-" * 20)

Tek Boyutlu Dizi:
Dizi: [1 2 3 4 5]
Şekil: (5,)
Boyut: 1
Veri Tipi: int64
--------------------
İki Boyutlu Dizi:
Dizi: [[1 2 3]
 [4 5 6]]
Şekil: (2, 3)
Boyut: 2
Veri Tipi: int64
--------------------
Üç Boyutlu Dizi:
Dizi: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Şekil: (2, 2, 2)
Boyut: 3
Veri Tipi: int64
--------------------


**Reasoning**:
Create arrays using `np.zeros`, `np.ones`, and `np.arange` and display their properties as requested in the instructions.



In [10]:
# 5. np.zeros, np.ones ve np.arange kullanarak farklı diziler oluşturun ve özelliklerini yazdırın.

# np.zeros kullanarak dizi oluşturma
sifirlar_dizisi = np.zeros((2, 3))
print("np.zeros ile Oluşturulan Dizi:")
print("Dizi:", sifirlar_dizisi)
print("Şekil:", sifirlar_dizisi.shape)
print("Boyut:", sifirlar_dizisi.ndim)
print("Veri Tipi:", sifirlar_dizisi.dtype)
print("-" * 20)

# np.ones kullanarak dizi oluşturma
birler_dizisi = np.ones((3, 2))
print("np.ones ile Oluşturulan Dizi:")
print("Dizi:", birler_dizisi)
print("Şekil:", birler_dizisi.shape)
print("Boyut:", birler_dizisi.ndim)
print("Veri Tipi:", birler_dizisi.dtype)
print("-" * 20)

# np.arange kullanarak dizi oluşturma
aralik_dizisi = np.arange(10)
print("np.arange ile Oluşturulan Dizi:")
print("Dizi:", aralik_dizisi)
print("Şekil:", aralik_dizisi.shape)
print("Boyut:", aralik_dizisi.ndim)
print("Veri Tipi:", aralik_dizisi.dtype)
print("-" * 20)

# np.arange ile belirli bir adım aralığı kullanarak dizi oluşturma
aralik_adimli_dizi = np.arange(0, 10, 2)
print("np.arange (Adımlı) ile Oluşturulan Dizi:")
print("Dizi:", aralik_adimli_dizi)
print("Şekil:", aralik_adimli_dizi.shape)
print("Boyut:", aralik_adimli_dizi.ndim)
print("Veri Tipi:", aralik_adimli_dizi.dtype)
print("-" * 20)

np.zeros ile Oluşturulan Dizi:
Dizi: [[0. 0. 0.]
 [0. 0. 0.]]
Şekil: (2, 3)
Boyut: 2
Veri Tipi: float64
--------------------
np.ones ile Oluşturulan Dizi:
Dizi: [[1. 1.]
 [1. 1.]
 [1. 1.]]
Şekil: (3, 2)
Boyut: 2
Veri Tipi: float64
--------------------
np.arange ile Oluşturulan Dizi:
Dizi: [0 1 2 3 4 5 6 7 8 9]
Şekil: (10,)
Boyut: 1
Veri Tipi: int64
--------------------
np.arange (Adımlı) ile Oluşturulan Dizi:
Dizi: [0 2 4 6 8]
Şekil: (5,)
Boyut: 1
Veri Tipi: int64
--------------------


## Dizi i̇ndeksleme ve dilimleme

### Subtask:
NumPy dizilerinde elemanlara ve alt dizilere nasıl erişileceğini (indeksleme ve dilimleme) açıklayın ve örneklerle gösterin.


**Reasoning**:
Create a one-dimensional NumPy array as the first step of the subtask.



In [11]:
# 1. Tek boyutlu bir NumPy dizisi oluşturun
tek_boyutlu_dizi = np.array([10, 20, 30, 40, 50])
print("Tek Boyutlu Dizi:", tek_boyutlu_dizi)

Tek Boyutlu Dizi: [10 20 30 40 50]


**Reasoning**:
Access and print a specific element from the one-dimensional array using indexing, as requested in the instructions.



In [12]:
# 2. Bu tek boyutlu diziden belirli bir elemana indeksleme kullanarak erişin ve yazdırın.
print("Tek boyutlu dizinin ilk elemanı (index 0):", tek_boyutlu_dizi[0])
print("Tek boyutlu dizinin üçüncü elemanı (index 2):", tek_boyutlu_dizi[2])

Tek boyutlu dizinin ilk elemanı (index 0): 10
Tek boyutlu dizinin üçüncü elemanı (index 2): 30


**Reasoning**:
Access and print a subarray from the one-dimensional array using slicing, as requested in the instructions.



In [13]:
# 3. Bu tek boyutlu diziden bir alt diziye dilimleme kullanarak erişin ve yazdırın.
print("Tek boyutlu dizinin ilk 3 elemanı (dilimleme):", tek_boyutlu_dizi[:3])
print("Tek boyutlu dizinin 2. indexten sonrasına kadar (dilimleme):", tek_boyutlu_dizi[2:])
print("Tek boyutlu dizinin 1. indexten 4. indexe kadar (dilimleme):", tek_boyutlu_dizi[1:4])

Tek boyutlu dizinin ilk 3 elemanı (dilimleme): [10 20 30]
Tek boyutlu dizinin 2. indexten sonrasına kadar (dilimleme): [30 40 50]
Tek boyutlu dizinin 1. indexten 4. indexe kadar (dilimleme): [20 30 40]


In [14]:
# 4. İki boyutlu bir NumPy dizisi oluşturun
iki_boyutlu_dizi = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("\nİki Boyutlu Dizi:")
print(iki_boyutlu_dizi)


İki Boyutlu Dizi:
[[10 20 30]
 [40 50 60]
 [70 80 90]]


**Reasoning**:
Demonstrate slicing on a two-dimensional NumPy array, as requested in the instructions for the "Dizi İndeksleme ve Dilimleme" subtask.

In [ ]:
# 6. İki boyutlu diziden alt dizilere dilimleme kullanarak erişin ve yazdırın.

# İlk satırı dilimleme
print("İki boyutlu dizinin ilk satırı:", iki_boyutlu_dizi[0, :])

# İkinci sütunu dilimleme
print("İki boyutlu dizinin ikinci sütunu:", iki_boyutlu_dizi[:, 1])

# Belirli bir alt matrisi dilimleme (ilk 2 satır, ilk 2 sütun)
print("İki boyutlu dizinin ilk 2 satır ve ilk 2 sütunu:\n", iki_boyutlu_dizi[:2, :2])

# 1. satırdan 2. satıra kadar (dahil) ve 1. sütundan sonuna kadar dilimleme
print("İki boyutlu dizinin 1. satırdan 2. satıra kadar ve 1. sütundan sonuna kadar:\n", iki_boyutlu_dizi[1:3, 1:])